{% set name = "weightedcalcs" %}
{% set version = "0.1.1" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "358c42eaa4cd94c70d57104ada0ead7694cd1d9be5fa8f02cb9213de2e68c989" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pandas >=0.19

  run:
    - python
    - pandas >=0.19

test:
  imports:
    - weightedcalcs

about:
  home: https://github.com/jsvine/weightedcalcs
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: 'Pandas-based utility to calculate weighted means, medians, distributions, standard deviations, and more.'
  dev_url: https://github.com/jsvine/weightedcalcs
  doc_url: https://github.com/jsvine/weightedcalcs

extra:
  recipe-maintainers:
    - pmlandwehr
