travis:
  secure:
    BINSTAR_TOKEN: kLbxQMPV+VjaVn6536u1V5paUj8moKbsKufFVnrGXYn4brTKPsLFuj5+7Y8pxtGSgYouqQQNV0cixtT2Sq4rG65YzSMLlGF1Qrj13XwrjJgzSKrl4QlDIBvxmzehMJPAJRxZiDS8Fpzs7feNH7QhUm3LOPpcKe/SxNxWmBHgmhiv1zKRxu3F6O6hX/+ygzAz3FtCHH6E9a0cKt1PkgzG7VxPKjJhkKBXqy1t3RlqerE9aHX5W11bvGHPGjXHBUzHWQydsB0JJCLpfZR0yu/x/492i1F+sBuv01s54Yw/RH+8MCdzHhhEnqsY0KY6kO6wXLt3TDB2JXi3bzdzP3Kd7OPUzI4ZM615qEny4yCCjNkUrmCH7mzfcXQ9Qi2YoJh8ddi1ZbXqjRRVyBL6OxPtAJMFm8oxB8EScPpuZ9bQOZQiUWtaF61w3KDUYUMyS/YKy5ivU4f6OPVRcOpAkisugFZ4uU3vEEWNtXkqjeWWUON875h5R2jd7s3th6pzUTajgazchwikNjubQv5z5ms4ckj+UpsIwhzECkH6tTptry0OCDcNd+Gj5REquQyN5qtGGwgp5c5h3LoDrCQS8xF8NP+eoX1diTQcbhFUau1ig8OTOzgUgq8gJtUk6cWp45BobTDi+Ybdlelatfcr6w2y4a34g7zrB1klg0q0nsPzR9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
