travis:
  secure:
    BINSTAR_TOKEN: FQ2I+dsd3DoOc6eg36bh3L8duB6jBWP69Fhyk4qTTS/kZLOJGK3DrOB4v4bjwZ/qlkQHf65qFEIKZbjEsGmRM8X6CJxvkf9UUykt//polGNS/QnHIJDId+9FjU1B2sKjeBxUKM3wJdL2O023rQC7aQ+tmQmRuBn6TAQWJIO9xQTmj/O/O8yfhMQlLf3/9jeXMvYRovbELnpgtET7YYXOFCpnu7Le/TrotdLOc5dGHVrOZ55Tp2Ae88iaOlkqiHVThYJnhJH0mnzapg2gzMKe0LXn7MHtJGCYp7KXgE91IYKL/pCu0urq20I6q4nfernI+aS4uDv9tqmthwLm78EG9eeSpy8rznaHzQ3S76mtDhCnNU3dpxIXZDYOJHkaqz1wkSmhh50GdAFyrENJKMqy5D5VchpyikEumw+0h48CmdP2Qaz3sYLLLFRB2t6QTKzfEOTa/cSJv22zfTheHd2uk1fJ94u1KtTAvFLgNERbL58zBT+XN8Qvyvic0zmFjxEFnoUlH+TiVGT55lWr21w5TSXuml9O1pN8+VCEtHj0ALW6+UiXfJup5F0MA2XPjkJuL9UH2EQjL2kuwim1jE1pusDP/OA3ypMmFA/dd7dB8rH9xd/PmC5IB97NPAnKTr8NC4YYhrHP9bBcspfNoJg/uYycwKOo3EU8s5zScz9ScR8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
